name: build & test

on:
  push:
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 10m
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: build
        run: go build -v ./...
      - name: test
        run: go test -gcflags=-l -v  -coverprofile=coverage.txt -covermode=atomic ./...

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v3
